export enum MaterialE {
    Cotton = 'Cotton',
    Wool = 'Wool',
    Polyester = 'Polyester',
    Nylon = 'Nylon',
    Silk = 'Silk',
    Denim = 'Denim',
    Leather = 'Leather',
    Fur = 'Fur',
    Linen = 'Linen',
    Velvet = 'Velvet',
    Rayon = 'Rayon',
    Spandex = 'Spandex',
    Acrylic = 'Acrylic',
    Cashmere = 'Cashmere',
    Angora = 'Angora',
    Mohair = 'Mohair',
}